name: Build and Release Plugins

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies (Dashboard)
        run: |
          cd ./dashboard-plugin-folder
          composer install --no-dev --optimize-autoloader

      - name: Install Dependencies (Bridge)
        run: |
          cd ./bridge-plugin-folder
          composer install --no-dev --optimize-autoloader

      - name: Create Dashboard Zip
        run: |
          mkdir wp-maintenance-dashboard
          cp -r ./dashboard-plugin-folder/* ./wp-maintenance-dashboard/
          zip -r owwmn.zip ./wp-maintenance-dashboard -x "*.git*" ".github*"

      - name: Create Bridge Zip
        run: |
          mkdir wp-maintenance-bridge
          cp -r ./bridge-plugin-folder/* ./wp-maintenance-bridge/
          zip -r owwmn-child.zip ./wp-maintenance-bridge -x "*.git*" ".github*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            owwmn.zip
            owwmn-child.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
